#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: debug
    type: boolean
    default: false

  - name: downloadedNugetPath # path to the downloaded nuget files
    type: string

  - name: nugetPackageVersion
    type: string
    default: $(NugetPackageVersion)

steps:
- template: add-nuget-feed-step.yml@self
  parameters:
    debug: ${{ parameters.debug }}
    key: 'Package Source'
    value: ${{ parameters.downloadedNugetPath }}
    feedType: Local

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGets'
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj -t:restore'
    feedsToUse: 'select'

- powershell: |
    $Doc = [xml](Get-Content "./Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj")
    $parent_xpath = '/Project/ItemGroup/ProjectReference'
    $node = $Doc.SelectSingleNode($parent_xpath)
    $parentNode = $node.ParentNode
    while($node -ne $null) {
        $node.ParentNode.RemoveChild($node)
        $node = $Doc.SelectSingleNode($parent_xpath)
    }

    $parent_xpath = '/Project/ItemGroup/PackageReference[@Include="Microsoft.Data.SqlClient"]'
    $node = $Doc.SelectSingleNode($parent_xpath)
    
    if($node -ne $null){
        $node.Version="${{parameters.nugetPackageVersion }}"
    }
    else{
        $packagerefnode = $doc.createelement("packagereference")
        $value = $doc.selectsinglenode('/project/itemgroup/projectreference')
        $attrinclude = $doc.createattribute("include")
        $attrinclude.value = "microsoft.data.sqlclient"
        $attrversion = $doc.createattribute("version")
        $attrversion.value = "${{parameters.nugetPackageVersion }}"
        $packagerefnode.attributes.append($attrinclude)
        $packagerefnode.attributes.append($attrversion)
        $parentNode.AppendChild($packageRefNode)
    }

    $currentFolder = Get-Location
    $filePath = Join-Path $currentFolder "Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj"
    $Doc.Save($filePath)
  workingDirectory: 'src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider'
  displayName: 'Update AKV Project Ref to Package Ref (.NET Framework/Core)'
